#!/bin/bash
codecov=0
while test $# -gt 0; do
    case "$1" in
        -c)
            echo Running code coverage suite
            codecov=1
            shift
            ;;
        *)
            break;
            ;;
    esac
done
mkdir build
cd build
if [ $codecov == 1 ]; then
    cmake .. -G "Unix Makefiles" -DENABLE_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug
    make
    cd bin
    xvfb-run ./libra &
    cd ..
    sleep 15
    killall libra
    gcovr -x -o coverage_report.xml --object-directory CMakeFiles/libra.dir/src/ -r ../src/
else
    cmake .. -G "Unix Makefiles"
    make
    make install
fi
